### ISSUE TITLE
demo test cases get stuck in pend state when attempting to run

### ISSUE THREAD

**Issue by toma010** [Luxoft/Twister#112]

**Comment by mtkuntz** [comment]
usr_srv.log logs this every 30 secs:
14-03-28 14:05:04  WARNING  _ERROR_ Cannot find file `/home/toma10/twister/logs/EP-1001_CLI.log`! [Errno 2] No such file or directory: '/home/toma10/twister/logs/EP-1001_CLI.log'
14-03-28 14:05:04  WARNING  _ERROR_ Cannot find file `/home/toma10/twister/logs/EP-1001_CLI.log`! [Errno 2] No such file or directory: '/home/toma10/twister/logs/EP-1001_CLI.log'
14-03-28 14:05:05  WARNING  _ERROR_ Cannot find file `/home/toma10/twister/logs/EP-1001_CLI.log`! [Errno 2] No such file or directory: '/home/toma10/twister/logs/EP-1001_CLI.log'

cat client_log.log
2014-Mar-28 14-03-14    Hello username `toma10`!
2014-Mar-28 14-03-14    Starting Twister Client...
2014-Mar-28 14-03-14    Sniffer eth = `eth0`.
2014-Mar-28 14-03-14    Building the EP list for this machine...
2014-Mar-28 14-03-14    Section `PACKETSNIFFERPLUGIN` is not a valid EP, because it needs CE_IP and CE_PORT.
2014-Mar-28 14-03-14    EP `EP-1001` doesn't have a HOST filter, so is valid.
2014-Mar-28 14-03-14    EP `EP-1002` doesn't have a HOST filter, so is valid.
2014-Mar-28 14-03-14    EP `EP-1003` doesn't have a HOST filter, so is valid.
2014-Mar-28 14-03-14    EP `EP-1004` doesn't have a HOST filter, so is valid.
2014-Mar-28 14-03-14    EP `EP-1005` doesn't have a HOST filter, so is valid.
2014-Mar-28 14-03-14    Found `5` EPs: ['EP-1001', 'EP-1002', 'EP-1003', 'EP-1004', 'EP-1005'].
2014-Mar-28 14-03-14    Starting Client Service register on `['127.0.0.1', 'localhost', 'pearl326', '167.254.241.70']`...
2014-Mar-28 14-03-14    ------- EPs to register -------
2014-Mar-28 14-03-14    { '127.0.0.1:8000': [ 'pearl326_EP-1005',
                      'pearl326_EP-1004',
                      'pearl326_EP-1001',
                      'pearl326_EP-1003',
                      'pearl326_EP-1002']}
2014-Mar-28 14-03-14    -------------------------------
2014-Mar-28 14-03-14    Register EPs function finished.
        If not all CE connections are made, they will be created asynchronously.
2014-Mar-28 14-03-14    ### Will REGISTER EPs on CE `127.0.0.1:8000` :: `['pearl326_EP-1005', 'pearl326_EP-1004', 'pearl326_EP-1001', 'pearl326_EP-1003', 'pearl326_EP-1002']` ###

2014-Mar-28 14-03-14    Client Debug: Connected to CE at `127.0.0.1:8010`...
2014-Mar-28 14-03-14    Client Debug: Authentication successful!
2014-Mar-28 14-03-16    ClientService: Hello `127.0.0.1`!
2014-Mar-28 14-03-16    Client Debug: Register EPs successful!
2014-Mar-28 14-03-16    ### Success REGISTER EPs on CE `127.0.0.1:8000` :: `['pearl326_EP-1005', 'pearl326_EP-1004', 'pearl326_EP-1001', 'pearl326_EP-1003', 'pearl326_EP-1002']` ###

**Comment by bogdanpopescu** [comment]
@mtkuntz 
Fix delivered on 10th April. Please test.
