### ISSUE TITLE
run button is disabled  & applet are not loading FF in ubuntu

### ISSUE THREAD

**Issue by ravichandra66** [Luxoft/Twister#168]
Hi ,
 i have installed twister frame .i have two issue 
1. applet are not loading FF in ubuntu
2. applet are loading in IE and test run button is disabled . not able to run tc

**Comment by croqaz** [comment]
Hello @ravichandra66 ,

The applet is not running in Firefox because you didn't activate the Java plugin in Firefox.

The plugins should look something like this:

![screenshot from 2015-02-12 10 06 25](https://cloud.githubusercontent.com/assets/1748317/6164334/d5c0cc30-b2a6-11e4-9885-18e1ef44e030.png)

Java is the first one from print screen.

About not being able to run tests, because `Run` is disabled, please provide us the logs from server and client.
The server logs are by default at  /opt/twister/server_log.log  and client at  ~/twister/client_log.log.

Any error should be in there.
