### ISSUE TITLE
how excutest test script with argumnest 

### ISSUE THREAD

**Issue by ravichandra66** [Luxoft/Twister#171]
Hi team , 

 I want execute the some script with test argument .please let me know how pass argument  though 
Twister UI 

thanks 
Ravichandra

**Comment by sravanmedarapu** [comment]
Hi Ravichandra,

We are trying to install the Twister framework on Ubuntu 12.04,  but we are seeing some errors while logging in to the twister application. 

We are able to install  the Framework successfully and we ran the twister server and client from below respective locations as well.

      ->  Start Twister server form the path:  /opt/twister/bin/start_server 
       ->  Start Twister client  from the path: home/user/twister/bin; ./start_client start

But while logging in to the application ( http://localhost/twister), we are getting the error message as “CE is not running, please start CE in order for Twister Framework to run properly” (Refer attachment) and  we are seeing the error message while starting the server saying “import *  File "/opt/twister/common/helpers.py", line 41, in <module>    from Crypto.Protocol.KDF import PBKDF2 ImportError: No module named KDF” but it was installed .

Please refer the attached server logs along with Issue screenshot and suggest the way to move forward.

Few More details regarding our installation environment :

 Installed framework in UBUNTU 12.04 
 Python 2.7.3 version
 Oracle Java 1.7 version
 Apahce2 installed
 Mysql DB

And we also tried in Ubuntu 13.10 version as well we are seeing the same error message. 


Can you please give me some suggestion on this.

**Comment by croqaz** [comment]
Hello @ravichandra66

In order to add arguments to a test, first select the test in the applet, then you have 2 options:

![screenshot from 2015-02-17 16 25 08](https://cloud.githubusercontent.com/assets/1748317/6229666/cbd83ea0-b6c1-11e4-83e1-960f975cc4ce.png)

You can edit properties and then, in the test, you can view them using the `PROPERTIES` variable,

or you can add parameters and in the test, you can view them using `import sys; print sys.argv`.
