### ISSUE TITLE
Central Engine cannot properly create logfiles for users that use nfs for the home directory

### ISSUE THREAD

**Issue by JimCamp** [Luxoft/Twister#20]
Our users home directory and default log directory is a nfs mount. The root user on a CE server does not have root permissions on nfs directories. I think the CE will have to spawn a task that runs as the logged in user to create the logfiles and .twister_cache file etc.

**Comment by bogdanpopescu** [comment]
The solution for this is to create a NIS group and to set this group for all users that need to run Twister client. 
This group have to be imported on all machines where NIS is runing. To import the group on a machine, the /etc/passwd file on that machine has to contain at the end the following entry "+@<group_name>::::::/bin/bash" - without the quotes. The file /etc/group has to contain at the end the following entry "+<group_name>:::" - without the quotes.
That should be all configuration in terms of NIS. 
Now, after the twister server and clients are installed, the group owner has to be set recursively to the defined group, using chmod command. That allows all user part of the group to read/write/execute the client and server ( including  log files ).
In order to make sure that all files created at run time can be read/write by the users in the group, the umask for every user has to be set to 002. This can be set automatically at login time, by creating a .profile file in user home and setting umask 002.
And that should be all

NOTE: all these operations where verified on Ubuntu 12.04.

**Comment by JimCamp** [comment]
This is still not properly fixed in 7/30/2012 delivery

**Comment by JimCamp** [comment]
passes on 2.024
