### ISSUE TITLE
Central Engine Not responding if any of the testcase has a property named "type" <BUG> <Priority 1>

### ISSUE THREAD

**Issue by baluthomas** [Luxoft/Twister#53]
When the user adds a property named 'type' for a test case the CE will not work properly after one execution.

And if the user add a property named 'status', the getFileVariable function will return returnstatus of the testcase rather than the value passed by the user.
1. If user adds a property for a test named 'type' the central engine get confused by the property defined by the user and the 'type' key in fileinfo object
2. Line 406, CentralEngineClasses.py,

data = self.project.getFileInfo(user, epname, file_id)
Here the data Dict is
 {'test1': 'type_test', 'status': 1, 'Runnable': 'true', 'dependancy': '', 'file': '/root/twister/demo/testsuite-python/getParam.py', 'status': 'myStatus', 'suite': '101', 'type': 'file'}
it should be something like 
{'test1': 'type_test', 'status': 1, 'Runnable': 'true', 'dependancy': '', 'file': '/root/twister/demo/testsuite-python/getParam.py', 'test_property' : {'status' : 'myStatus'}, 'suite': '101', 'type': 'file'}

**Comment by croqaz** [comment]
Hello,
The properties: `type`, `suite`, `file`, `dependency`, `status`, `Runnable`, `Optional`, `setup_file`, `teardown_file` and `param` are reserved for internal use and must NOT be used. This information will appear in the most recent version, in the documentation.
In order to access the properties defined in the applet for each file, you should use PROPERTIES, inside a test file. The PROPERTIES is a dictionary that contains all props defined in the GUI for the current file. This information will also appear in the most recent documentation.
Please don't change the central engine internal variables, it will most likely create a weird behavior.

**Comment by bogdanpopescu** [comment]
@baluthomas 
Can we close the issue ?
