### ISSUE TITLE
There are two issues with Testbed editing

### ISSUE THREAD

**Issue by mtkuntz** [Luxoft/Twister#96]
There are two issues with Testbed editing.
The GUI view is not refreshed until the user logs out and log in. The TestBed view should be refreshed simply by navigating from/to Test Bed Configuration panel.

There needs to be better protection if the user has not navigated off the view and potentially affect other's changes.
if user A and user B are both on Test Beds, they start with the same view.
User B makes changes, and its committed.
User A then also makes changes, and its committed.
User A just overwrote changes made by B.
User A should be warned that the Test Bed has changed since last viewed, and have the opportunity to Cancel.

**Comment by toma010** [comment]
Partial fix only is not a real solution.

Active users should only show those who have made changes to the Testbed not those who are only browsing.

This really needs to behave like an editor and not save automatically. A save feature should be added and should know if the file on disk has been changed since the local changes have been made.

**Comment by mtkuntz** [comment]
Agree that this is a partial fix - we need a more robust solution. OK to Close for now.
